### ISSUE TITLE
tech blog のテーマをカスタマイズする

### ISSUE THREAD

**Issue by mserizawa** [kufu/saiyo-tasukete#3]
歴史的な経緯によりはてなブログのデフォルトテーマを使っていたが、もっとオリジナリティを出したいのでカスタマイズしたい。

**Comment by masuP9** [comment]
一旦プロトタイプを作ったので、反映しつつリニューアルしたい。

![tech smarthr jp_entry_2021_05_12_120243](https://user-images.githubusercontent.com/6724665/117920424-c9774500-b329-11eb-9989-9ae77e4d0905.png)

**Comment by masuP9** [comment]
反映したのでクローズします！

シンタックスハイライトをSmartHRカラーにしたけど、Rubyが分からなくて読みやすさわからなさすぎる。
<img width="528" alt="Rubyのコードのシンタックスハイライト" src="https://user-images.githubusercontent.com/6724665/121371137-48d35500-c978-11eb-813d-e6ca1a573489.png">


採用情報とカジュアル面談へのリンク追加した。プロフィール画像を変えたい。
<img width="738" alt="プロフィールモジュールとリンクモジュールのスクショ。" src="https://user-images.githubusercontent.com/6724665/121371294-686a7d80-c978-11eb-8610-416b92e6a7fa.png">
